mutation CreateClient($name: NameCreateOneInput!, $legalForm: ID!, $email: String, $phone: String, $address: AddressCreateOneInput!, $company: String) {
  createClient(
    name: $name,
    legalForm: $legalForm,
    email: $email,
    phone: $phone,
    address: $address,
    company: $company
  ) {
    id
  }
}