{
    meClients {
        id
        name {
            firstname
            lastname
        }
        email
        phone
        legalForm {
            id
        }
        address {
            street
            street2
            postalcode
            city
            country
        }
        company
    }
}