mutation UpdateClient($id: ID!, $name: NameCreateOneInput!, $legalForm: ID, $phone: String, $email: String, $address: AddressCreateOneInput!, $company: String){
    updateClient(
        id: $id,
        name: $name,
        legalForm: $legalForm,
        phone: $phone,
        email: $email,
        address: $address
        company: $company
    ){
        id
    }
}