mutation UpdateClient($id: ID!, $firstname: String!, $lastname: String!, $legalForm: ID, $phone: String, $email: String, $street: String!, $street2: String, $postalcode: String!, $city: String!, $country: String!, $company: String){
    updateClient(
        id: $id,
        name: { create: { firstname: $firstname, lastname: $lastname } },
        legalForm: $legalForm,
        phone: $phone,
        email: $email,
        address: {
              create: {
                street: $street,
                street2: $street2,
                postalcode: $postalcode,
                city: $city,
                country: $country,
              }
            }
        company: $company
    ){
        id
    }
}