export const errors = {
    "AUTH001": "L'authentification a échoué.",
    "AUTH002": "Token manquant.",
    "AUTH003": "Vous n'êtes pas administrateur.",
    "TokenExpiredError": "Le token est expiré.",
    "JsonWebTokenError": "Le token est invalide.",
    "NotBeforeError": "JWT n'est pas actif.",
    "USER001": "L'utilisateur n'existe pas.",
    "ME003": "Impossible de supprimer votre compte.",
    "CLIENT001": "Impossible de créer le client.",
    "CLIENT002": "Impossible de mettre à jour le client.",
    "CLIENT003": "Impossible de supprimer le client.",
    "ESTIMATE001": "Impossible de créer le devis.",
    "ESTIMATE002": "Impossible de mettre à jour le devis.",
    "ESTIMATE003": "Impossible de valider le devis.",
    "ESTIMATE004": "Impossible de supprimer le devis.",
    "INVOICE001": "Impossible de créer la facture.",
    "INVOICE002": "Impossible de mettre à jour la facture.",
    "INVOICE003": "Impossible de valider la facture.",
    "INVOICE004": "Impossible de supprimer la facture.",
    "LEGALFORM001": "Impossible de créer la forme juridique.",
    "LEGALFORM002": "Impossible de mettre à jour la forme juridique.",
    "LEGALFORM003": "Impossible de supprimer la forme juridique.",
    "PRODUCT001": "Impossible de créer le produit/prestation.",
    "PRODUCT002": "Impossible de mettre à jour le produit/prestation.",
    "PRODUCT003": "Impossible de supprimer le produit/prestation.",
};